# Generated by Django 6.0.2 on 2026-02-07 07:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vente', '0003_commande_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_nom', models.CharField(blank=True, default='', max_length=120)),
                ('signature_titre', models.CharField(blank=True, default='', max_length=120)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='facturation/signatures/')),
                ('footer_note', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facturation - Settings',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=40, unique=True)),
                ('date_emission', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='vente.commande')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
