# Generated by Django 6.0.2 on 2026-02-10 11:25

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vente', '0004_alter_commande_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_charge', models.DateField(default=django.utils.timezone.localdate)),
                ('libelle', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='PAYEE', max_length=20)),
                ('mode_paiement', models.CharField(choices=[('CASH', 'Cash'), ('MVOLA', 'MVola'), ('ORANGE_MONEY', 'Orange Money'), ('VISA', 'VISA'), ('AUTRE', 'Autre')], default='CASH', max_length=20)),
                ('piece', models.FileField(blank=True, null=True, upload_to='charges/pieces/')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='vente.commande')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_creees', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='charge.chargecategorie')),
            ],
            options={
                'ordering': ['-date_charge', '-created_at'],
                'indexes': [models.Index(fields=['date_charge'], name='charge_char_date_ch_93f9e7_idx'), models.Index(fields=['statut'], name='charge_char_statut_de06e3_idx'), models.Index(fields=['categorie'], name='charge_char_categor_29284a_idx')],
            },
        ),
    ]
