# Generated by Django 6.0.2 on 2026-02-07 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Mon Application', max_length=120)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration globale',
                'verbose_name_plural': 'Configuration globale',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('lien', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuration/pages/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='configuration.appconfiguration')),
            ],
            options={
                'ordering': ['ordre', 'id'],
                'unique_together': {('config', 'nom')},
            },
        ),
    ]
