# Generated by Django 6.0.2 on 2026-02-10 08:36

import django.core.validators
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='numero_telephone',
            field=models.CharField(blank=True, default='', max_length=30, validators=[django.core.validators.RegexValidator(message='Numéro invalide. Exemple: +261 34 00 000 00', regex='^\\+?[0-9 \\-]{6,20}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='users/couverture/'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='users/profil/'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COMMERCIALE', 'Commerciale'), ('COMMUNITY_MANAGER', 'Community manager')], default='COMMERCIALE', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('AUTRE', 'Autre')], default='', max_length=10),
        ),
    ]
