# Generated by Django 6.0.2 on 2026-02-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_alter_user_managers_user_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('UTILISATEUR', 'Utilisateur'), ('COMMERCIALE', 'Commerciale'), ('COMMUNITY_MANAGER', 'Community manager')], default='COMMERCIALE', max_length=32),
        ),
    ]
