# Generated by Django 6.0.2 on 2026-02-09 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vente', '0003_commande_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('A_PREPARER', 'À préparer'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée'), ('REPORTEE', 'Reportée')], default='A_PREPARER', max_length=20)),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('date_reelle', models.DateTimeField(blank=True, null=True)),
                ('raison', models.CharField(blank=True, default='', max_length=255)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_livraison', to='vente.commande')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LivraisonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_statut', models.CharField(blank=True, default='', max_length=20)),
                ('to_statut', models.CharField(blank=True, default='', max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraison_events', to=settings.AUTH_USER_MODEL)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='conflivraison.livraison')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
