# Generated by Django 6.0.2 on 2026-02-06 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0003_article_quantite_stock'),
        ('client', '0001_initial'),
        ('livraison', '0002_alter_fraislivraison_lieu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision_lieu', models.CharField(blank=True, default='', max_length=255)),
                ('client_nom', models.CharField(blank=True, default='', max_length=150)),
                ('client_contact', models.CharField(blank=True, default='', max_length=100)),
                ('client_adresse', models.CharField(blank=True, default='', max_length=255)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('CONFIRMEE', 'Confirmée'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='client.client')),
                ('frais_livraison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='livraison.fraislivraison')),
                ('lieu_livraison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='livraison.lieulivraison')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commandes', to='article.article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='vente.commande')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
