# Generated by Django 6.0.2 on 2026-02-07 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('vente', '0002_commande_date_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='configuration.page'),
        ),
    ]
