# Generated by Django 6.0.2 on 2026-02-07 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vente', '0002_commande_date_livraison'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('mode', models.CharField(blank=True, choices=[('ESPECE', 'Espèce'), ('MVOLA', 'MVola'), ('ORANGE_MONEY', 'Orange Money')], default='', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('encaisse_le', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encaissement', to='vente.commande')),
                ('encaisse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encaissements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
