# Generated by Django 6.0.2 on 2026-02-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quantite_stock',
            field=models.IntegerField(default=0),
        ),
    ]
