# Generated by Django 6.0.2 on 2026-02-06 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LieuLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('categorie', models.CharField(choices=[('VILLE', 'Ville'), ('PERIPHERIE', 'Périphérie'), ('PLUS_PERIPHERIE', 'Plus périphérie'), ('PROVINCE', 'Province'), ('AUTRE', 'Autre (manuel)')], default='VILLE', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FraisLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frais_calculé', models.PositiveIntegerField(default=0)),
                ('frais_override', models.PositiveIntegerField(blank=True, null=True)),
                ('frais_final', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frais', to='livraison.lieulivraison')),
            ],
        ),
    ]
