# Generated by Django 6.0.2 on 2026-02-06 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraislivraison',
            name='lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frais_lignes', to='livraison.lieulivraison'),
        ),
    ]
