# Generated by Django 6.0.2 on 2026-02-06 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0002_alter_fraislivraison_lieu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fraislivraison',
            old_name='frais_calculé',
            new_name='frais_calcule',
        ),
        migrations.AlterField(
            model_name='fraislivraison',
            name='lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frais', to='livraison.lieulivraison'),
        ),
    ]
